import { ERROR, OFF } from '../severity.js';

export const suggestionRules = {
  'vue/match-component-import-name': [ERROR],
  // 'vue/max-lines-per-block': [WARN, {
  //   template: 120,
  //   script: 120,
  //   style: 120,
  //   skipBlankLines: true,
  // }],
  'vue/no-arrow-functions-in-watch': [ERROR],
  'vue/no-async-in-computed-properties': [ERROR],
  'vue/no-child-content': [ERROR],
  'vue/no-computed-properties-in-data': [ERROR],
  'vue/no-deprecated-data-object-declaration': [ERROR],
  'vue/no-deprecated-destroyed-lifecycle': [ERROR],
  'vue/no-deprecated-dollar-listeners-api': [ERROR],
  'vue/no-deprecated-dollar-scopedslots-api': [ERROR],
  'vue/no-deprecated-events-api': [ERROR],
  'vue/no-deprecated-filter': [ERROR],
  'vue/no-deprecated-functional-template': [ERROR],
  'vue/no-deprecated-html-element-is': [ERROR],
  'vue/no-deprecated-inline-template': [ERROR],
  'vue/no-deprecated-model-definition': [ERROR],
  'vue/no-deprecated-props-default-this': [ERROR],
  'vue/no-deprecated-router-link-tag-prop': [ERROR, { components: ['RouterLink'] }],
  'vue/no-deprecated-v-bind-sync': [ERROR],
  'vue/no-deprecated-v-on-native-modifier': [ERROR],
  'vue/no-deprecated-v-on-number-modifiers': [ERROR],
  'vue/no-deprecated-vue-config-keycodes': [ERROR],
  'vue/no-dupe-keys': [ERROR],
  'vue/no-dupe-v-else-if': [ERROR],
  'vue/no-duplicate-attributes': [ERROR],
  'vue/no-export-in-script-setup': [ERROR],
  'vue/no-expose-after-await': [ERROR],
  'vue/no-lone-template': [ERROR],
  'vue/no-multiple-slot-args': [ERROR],
  'vue/no-parsing-error': [ERROR],
  'vue/no-ref-object-reactivity-loss': [ERROR],
  'vue/no-required-prop-with-default': [ERROR],
  'vue/no-reserved-props': [ERROR],
  'vue/no-restricted-class': [OFF],
  'vue/no-shared-component-data': [ERROR],
  'vue/no-side-effects-in-computed-properties': [ERROR],
  'vue/no-template-key': [ERROR],
  'vue/no-template-target-blank': [ERROR],
  'vue/no-textarea-mustache': [ERROR],
  'vue/no-this-in-before-route-enter': [ERROR],
  'vue/no-use-computed-property-like-method': [ERROR],
  'vue/no-useless-template-attributes': [ERROR],
  'vue/no-v-for-template-key-on-child': [ERROR],
  'vue/no-v-text-v-html-on-component': [ERROR],
  'vue/prefer-prop-type-boolean-first': [ERROR],
  'vue/require-component-is': [ERROR],
  'vue/require-render-return': [ERROR],
  'vue/require-slots-as-functions': [ERROR],
  'vue/require-toggle-inside-transition': [ERROR],
  'vue/require-v-for-key': [ERROR],
  'vue/return-in-computed-property': [ERROR],
  'vue/return-in-emits-validator': [ERROR],
  'vue/v-if-else-key': [OFF],
  'vue/valid-attribute-name': [ERROR],
  'vue/valid-define-emits': [ERROR],
  'vue/valid-define-props': [ERROR],
  'vue/valid-next-tick': [ERROR],
  'vue/valid-template-root': [ERROR],
  'vue/valid-v-bind': [ERROR],
  'vue/valid-v-cloak': [ERROR],
  'vue/valid-v-else': [ERROR],
  'vue/valid-v-else-if': [ERROR],
  'vue/valid-v-for': [ERROR],
  'vue/valid-v-html': [ERROR],
  'vue/valid-v-if': [ERROR],
  'vue/valid-v-is': [ERROR],
  'vue/valid-v-memo': [ERROR],
  'vue/valid-v-model': [ERROR],
  'vue/valid-v-on': [ERROR],
  'vue/valid-v-once': [ERROR],
  'vue/valid-v-pre': [ERROR],
  'vue/valid-v-show': [ERROR],
  'vue/valid-v-slot': [ERROR],
  'vue/valid-v-text': [ERROR],
};
