import { ERROR, OFF, WARN } from '../severity.js';

export const commonRules = {
  '@typescript-eslint/adjacent-overload-signatures': ERROR,
  '@typescript-eslint/array-type': ERROR,
  '@typescript-eslint/await-thenable': ERROR,
  '@typescript-eslint/ban-ts-comment': ERROR,
  '@typescript-eslint/ban-tslint-comment': ERROR,
  // '@typescript-eslint/ban-types': ERROR,
  '@typescript-eslint/class-literal-property-style': ERROR,
  '@typescript-eslint/consistent-generic-constructors': ERROR,
  '@typescript-eslint/consistent-indexed-object-style': ERROR,
  '@typescript-eslint/consistent-type-assertions': ERROR,
  '@typescript-eslint/consistent-type-definitions': ERROR,
  '@typescript-eslint/consistent-type-exports': ERROR,
  '@typescript-eslint/consistent-type-imports': ERROR,
  '@typescript-eslint/explicit-function-return-type': OFF,
  '@typescript-eslint/explicit-member-accessibility': ERROR,
  '@typescript-eslint/explicit-module-boundary-types': OFF,
  // '@typescript-eslint/member-delimiter-style': ERROR,
  '@typescript-eslint/member-ordering': ERROR,
  '@typescript-eslint/method-signature-style': ERROR,
  '@typescript-eslint/naming-convention': [
    ERROR,
    {
      selector: 'default',
      // UPPER_CASE for, like example, consts from env files
      format: ['camelCase', 'UPPER_CASE'],
      leadingUnderscore: 'forbid',
      trailingUnderscore: 'forbid',
    },
    {
      selector: 'import',
      // PascalCase for components import
      format: ['camelCase', 'PascalCase'],
    },
    {
      selector: 'variable',
      // UPPER_CASE for, like example, consts from env files
      format: ['camelCase', 'UPPER_CASE'],
    },
    {
      selector: 'typeLike',
      format: ['PascalCase'],
    },
    {
      selector: 'objectLiteralProperty',
      // because of BE inconsistency
      format: null,
    },
  ],
  '@typescript-eslint/no-base-to-string': ERROR,
  '@typescript-eslint/no-confusing-non-null-assertion': ERROR,
  '@typescript-eslint/no-confusing-void-expression': ERROR,
  '@typescript-eslint/no-duplicate-enum-values': ERROR,
  '@typescript-eslint/no-duplicate-type-constituents': ERROR,
  '@typescript-eslint/no-dynamic-delete': ERROR,
  '@typescript-eslint/no-empty-interface': ERROR,
  '@typescript-eslint/no-explicit-any': WARN,
  '@typescript-eslint/no-extra-non-null-assertion': ERROR,
  '@typescript-eslint/no-extraneous-class': ERROR,
  '@typescript-eslint/no-floating-promises': ERROR,
  '@typescript-eslint/no-for-in-array': ERROR,
  '@typescript-eslint/no-import-type-side-effects': ERROR,
  '@typescript-eslint/no-inferrable-types': ERROR,
  '@typescript-eslint/no-invalid-void-type': ERROR,
  '@typescript-eslint/no-meaningless-void-operator': ERROR,
  '@typescript-eslint/no-misused-new': ERROR,
  '@typescript-eslint/no-misused-promises': [
    ERROR,
    {
      checksVoidReturn: false,
    },
  ],
  '@typescript-eslint/no-mixed-enums': ERROR,
  '@typescript-eslint/no-namespace': ERROR,
  '@typescript-eslint/no-non-null-asserted-nullish-coalescing': ERROR,
  '@typescript-eslint/no-non-null-asserted-optional-chain': ERROR,
  '@typescript-eslint/no-non-null-assertion': OFF,
  '@typescript-eslint/no-redundant-type-constituents': ERROR,
  '@typescript-eslint/no-require-imports': ERROR,
  '@typescript-eslint/no-this-alias': ERROR,
  '@typescript-eslint/no-unnecessary-boolean-literal-compare': ERROR,
  '@typescript-eslint/no-unnecessary-condition': ERROR,
  '@typescript-eslint/no-unnecessary-qualifier': ERROR,
  '@typescript-eslint/no-unnecessary-type-arguments': ERROR,
  '@typescript-eslint/no-unnecessary-type-assertion': ERROR,
  '@typescript-eslint/no-unnecessary-type-constraint': ERROR,
  '@typescript-eslint/no-unsafe-argument': WARN,
  '@typescript-eslint/no-unsafe-assignment': OFF,
  '@typescript-eslint/no-unsafe-call': WARN,
  '@typescript-eslint/no-unsafe-declaration-merging': ERROR,
  '@typescript-eslint/no-unsafe-enum-comparison': ERROR,
  '@typescript-eslint/no-unsafe-member-access': WARN,
  '@typescript-eslint/no-unsafe-return': OFF,
  '@typescript-eslint/no-useless-empty-export': ERROR,
  '@typescript-eslint/no-var-requires': ERROR,
  '@typescript-eslint/non-nullable-type-assertion-style': ERROR,
  '@typescript-eslint/parameter-properties': ERROR,
  '@typescript-eslint/prefer-as-const': ERROR,
  '@typescript-eslint/prefer-enum-initializers': ERROR,
  '@typescript-eslint/prefer-for-of': ERROR,
  '@typescript-eslint/prefer-function-type': ERROR,
  '@typescript-eslint/prefer-includes': ERROR,
  '@typescript-eslint/prefer-literal-enum-member': ERROR,
  '@typescript-eslint/prefer-namespace-keyword': ERROR,
  // maybe we will enable it later, after ending discuss in ts-eslint repo
  // https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue%20state%3Aopen%20prefer-nullish-coalescing
  '@typescript-eslint/prefer-nullish-coalescing': OFF,
  '@typescript-eslint/prefer-optional-chain': ERROR,
  '@typescript-eslint/prefer-readonly': ERROR,
  '@typescript-eslint/prefer-readonly-parameter-types': OFF,
  '@typescript-eslint/prefer-reduce-type-parameter': ERROR,
  '@typescript-eslint/prefer-regexp-exec': ERROR,
  '@typescript-eslint/prefer-return-this-type': ERROR,
  '@typescript-eslint/prefer-string-starts-ends-with': ERROR,
  '@typescript-eslint/prefer-ts-expect-error': ERROR,
  '@typescript-eslint/promise-function-async': ERROR,
  '@typescript-eslint/require-array-sort-compare': ERROR,
  '@typescript-eslint/restrict-plus-operands': ERROR,
  '@typescript-eslint/restrict-template-expressions': ERROR,
  '@typescript-eslint/sort-type-constituents': OFF,
  '@typescript-eslint/strict-boolean-expressions': OFF,
  '@typescript-eslint/switch-exhaustiveness-check': OFF,
  '@typescript-eslint/triple-slash-reference': ERROR,
  // '@typescript-eslint/type-annotation-spacing': ERROR,
  '@typescript-eslint/typedef': ERROR,
  '@typescript-eslint/unbound-method': ERROR,
  '@typescript-eslint/unified-signatures': ERROR,
};
