import { OFF } from '../severity.js';

import { suggestionRules } from '../javascript/suggestions.js';
import { possibleProblemRules } from '../javascript/possible-problems.js';

export const extensionsRules = {
  'class-methods-use-this': OFF,
  '@typescript-eslint/class-methods-use-this': suggestionRules['class-methods-use-this'],
  'default-param-last': OFF,
  '@typescript-eslint/default-param-last': suggestionRules['default-param-last'],
  'dot-notation': OFF,
  '@typescript-eslint/dot-notation': suggestionRules['dot-notation'],
  'init-declarations': OFF,
  '@typescript-eslint/init-declarations': suggestionRules['init-declarations'],
  'no-array-constructor': OFF,
  '@typescript-eslint/no-array-constructor': suggestionRules['no-array-constructor'],
  'no-empty-function': OFF,
  '@typescript-eslint/no-empty-function': suggestionRules['no-empty-function'],
  'no-implied-eval': OFF,
  '@typescript-eslint/no-implied-eval': suggestionRules['no-implied-eval'],
  'no-invalid-this': OFF,
  '@typescript-eslint/no-invalid-this': suggestionRules['no-invalid-this'],
  'no-loop-func': OFF,
  '@typescript-eslint/no-loop-func': suggestionRules['no-loop-func'],
  'no-magic-numbers': OFF,
  '@typescript-eslint/no-magic-numbers': suggestionRules['no-magic-numbers'],
  'no-redeclare': OFF,
  '@typescript-eslint/no-redeclare': suggestionRules['no-redeclare'],
  'no-restricted-imports': OFF,
  '@typescript-eslint/no-restricted-imports': suggestionRules['no-restricted-imports'],
  'no-shadow': OFF,
  '@typescript-eslint/no-shadow': suggestionRules['no-shadow'],
  'no-throw-literal': OFF,
  // '@typescript-eslint/no-throw-literal': suggestionRules['no-throw-literal'],
  'no-unused-expressions': OFF,
  '@typescript-eslint/no-unused-expressions': suggestionRules['no-unused-expressions'],
  'no-useless-constructor': OFF,
  '@typescript-eslint/no-useless-constructor': suggestionRules['no-useless-constructor'],
  'require-await': OFF,
  '@typescript-eslint/require-await': suggestionRules['require-await'],
  'no-return-await': OFF,
  '@typescript-eslint/return-await': suggestionRules['no-return-await'],

  'no-dupe-class-members': OFF,
  '@typescript-eslint/no-dupe-class-members': possibleProblemRules['no-dupe-class-members'],
  'no-loss-of-precision': OFF,
  '@typescript-eslint/no-loss-of-precision': possibleProblemRules['no-loss-of-precision'],
  'no-unused-vars': OFF,
  '@typescript-eslint/no-unused-vars': possibleProblemRules['no-unused-vars'],
  'no-use-before-define': OFF,
  '@typescript-eslint/no-use-before-define': possibleProblemRules['no-use-before-define'],
};
